FROM alpine:3.4

RUN apk --no-cache add nginx bash ca-certificates
COPY nginx.conf /etc/nginx/nginx.conf

ADD default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
